<?php
$defis = [
    "Peluche" => [
        "Je vais t'aimer de JulienPetri",
        "Je vais t'aimer de EstelleMca",
        "Version 1",
        "Version 2",
        "Je vais t'aimer de Anthony Walther",
        "Si j'étais président de AnthonyWalther",
        "Parle à ma main de AnthonyWalther",
        "Je voudrais un bonhomme de neige de AnthonyWalther",
        "Sous l'océan de AnthonyWalther",
        "Etre un homme comme vous de AnthonyWalther",
        "Comme d'habitude de EstelleMca",
        "La javanaise de Aurele32lab",
        "Quand j'étais chanteur de Delorean",
        "La vache de CarolGygi",
        "Gabby et les petits malins de Manou_ZIK",
    ],
    "Brosse à dent" => [
        "Aimer de EstelleMca",
        "Comme un boomerang de Anthony Walther",
        "Je suis venu te dire que je m'en vais de AnthonyWalther",
        "Version 1",
        "Version 2",
        "Version 3",
        "Version 4",
    ],
    "Aveugle" => [
        "Sous les sunlight des tropiques de AnthonyWalther",
        "Version numéro 1",
        "Version numéro 2",
        "Version numéro 3",
        "Version numéro 4",
        "Version numéro 5",
        "On va s'aimer de AnthonyWalther",
        "Version numéro 1",
        "Version numéro 2",
    ],
    "Edith Piaf" => [
        "Non je ne regrette rien de AnthonyWalther",
        "Version 1",
        "Version 2",
        "Version 3",
        "Version 4",
        "Mon Dieu de AnthonyWalther",
        "La vie en rose de AnthonyWalther",
        "Mon manège à moi de AnthonyWalther",
        "Milord de AnthonyWalther",
        "L'hymne à l'amour de AnthonyWalther",
        "Padam Padam de AnthonyWalther",
        "La foule de Klosept",
    ],
    "Casserole" => [
        "Seul de Yassou",
        "Je suis malade de cwWayenece",
        "L'hymne à l'amour de AnthonyWalther",
        "Les mots de EstelleMca",
        "Couleur menthalo de Nuage",
        "Avant toi de Nuage",
        "Je ne suis pas un héros de Manou_Zik",
        "Vous les copains de Guitou",
        "On se retrouvera de Elodie Baleyre",
        "L'hymne à l'amour de Julien Petri",
        "Belle de CarolGygi",
    ],
    "Crayon" => [
        "Je t'aime de AnthonyWalther",
        "Version numéro 1",
        "Version numéro 2",
        "Version numéro 3",
        "Version numéro 4",
    "Je t'aime de JulienPetri",
    ],
    "Goinfre" => [
        "Elle préfère l'amour en mer de Manou_ZIK",
        "La Banane de AnthonyWalther",
        "Pomme de Reinette de AnthonyWalther",
        "Les sucettes de Guitou",
    ],
    "Chimpmunk" => [],
    "Oxygène" => [],
    "Chèvre" => [],
    "Alcool" => [],
    "Hydratation" => [],
    "Langue" => [],
    "Ressort" => [],
    "Impro" => [],
    "Genre " => [],
    "Chips" => [],
    "Compil des Jean-Michel" => [],
];
include('defis.html');
?>